theme: jekyll-theme-tactile
title: Adyen Checkathon - Amsterdam 2019 - Team Five
description: This is the hackathon page for the Team Five. Here you'll find our contribution to the hackathon challenge.
